#! /usr/bin/python3
from PySide6.QtWidgets import QApplication
from PySide6.QtQuick import QQuickView
from PySide6.QtCore import QUrl, QObject, Slot, Signal, Property
import os
import sys
import subprocess
import shutil
import pwd
import grp
import gettext
gettext.textdomain('lliurex-access-control')
_= gettext.gettext

class Tunnel(QObject):

	def __init__(self):

		QObject.__init__(self)
		self.clearCache()

	#def __init	

	def clearCache(self):

		clear=False
		userHome=os.path.expanduser("~")
		versionFile=os.path.join(userHome,".config/lliurex-access-control.conf")
		cachePath1=os.path.join(userHome,".cache/lliurex-access-control")
		cachePath2=os.path.join(userHome,".cache/lliurex-access-control-gui.py")
		installedVersion=self.getPackageVersion()


		if not os.path.exists(versionFile):
			with open(versionFile,'w') as fd:
				fd.write(installedVersion)

			clear=True

		else:
			with open(versionFile,'r') as fd:
				fileVersion=fd.readline()

			if fileVersion!=installedVersion:
				with open(versionFile,'w') as fd:
					fd.write(installedVersion)
				clear=True
		
		if clear:
			if os.path.exists(cachePath1):
				shutil.rmtree(cachePath1)
			if os.path.exists(cachePath2):
				shutil.rmtree(cachePath2)

	#def clearCache

	def getPackageVersion(self):

		packageVersionFile="/var/lib/lliurex-access-control/version"
		pkgVersion=""

		if os.path.exists(packageVersionFile):
			with open(packageVersionFile,'r') as fd:
				pkgVersion=fd.readline().strip()

		return pkgVersion

	#def getPackageVersion

	def checkUser(self,user):

		isAdmin=False
		GROUPS=["admins","sudo"]
		gid = pwd.getpwnam(user).pw_gid
		groupsGids = os.getgrouplist(user, gid)
		userGroups = [ grp.getgrgid(x).gr_name for x in groupsGids ]

		for item in userGroups:
			if item in GROUPS:
				return True
				break

	#def checkUser

	@Slot(str)
	def onTicket(self,ticket):

		user=ticket.split(' ')[2]

		if self.checkUser(user):
			ticket=ticket.replace(' ','##U+0020##')
			os.system("python3 /usr/share/lliurex-access-control/lliurex-access-control-gui.py %s &"%ticket)
		else:
			text=_("You need administration privileges to run this application in this computer.")
			cmd='kdialog --icon lliurex-access-control --title "Lliurex-Access-Control" --passivepopup \
			"%s" 5'%text
			os.system(cmd)
		
		app.quit()
		
	#def on_ticket
	
#class Tunnel	

app = QApplication([])
app.setDesktopFileName("lliurex-access-control")
tunnel = Tunnel()
view = QQuickView()
view.rootContext().setContextProperty("tunnel", tunnel)
url = QUrl("/usr/share/lliurex-access-control/rsrc/login.qml")
view.setSource(url)
view.show()
ret=app.exec()
del view
del app
sys.exit(ret)
